/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2 */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetCellAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetCellAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetCaption
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetCaption
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetColumnDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetColumnDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetNColumns
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetNColumns
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetNRows
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetNRows
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetNSelectedCells
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetNSelectedCells
 (JNIEnv * env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetNSelectedColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetNSelectedColumns
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetNSelectedRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetNSelectedRows
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetRowDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetRowDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetSelectedCells
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetSelectedCells
(JNIEnv *, jobject );

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetSelectedColumns
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetSelectedColumns
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetSelectedRows
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetSelectedRows
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetSummary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetSummary
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalIsColumnSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalIsColumnSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalIsRowSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalIsRowSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalSelectRow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalSelectRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalSelectColumn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalSelectColumn
  (JNIEnv *, jobject, jint);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalUnselectRow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalUnselectRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalUnselectColumn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalUnselectColumn
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2
 * Method:    internalGetModelChange
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTable2_internalGetModelChange
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
