/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlinkCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlinkCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlink
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlink
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlinkIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlinkIndex
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
