/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
 * Method:    internalGetAccessibleAnchor
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink_internalGetAnchor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
 * Method:    internalGetAccessibleAnchorTarget
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink_internalGetAnchorTarget
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
 * Method:    internalGetStartIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink_internalGetStartIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
 * Method:    internalGetEndIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink_internalGetEndIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink
 * Method:    internalIsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHyperlink_internalIsValid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
