/* DO NOT EDIT THIS FILE - it is machine generated */
#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext.h"


IAccessibleHypertext* GetRef( JNIEnv *env, jobject jca){
    jclass cls = env->GetObjectClass(jca);
    jmethodID methID = env->GetMethodID(cls, "internalRef", "()I");
    return (IAccessibleHypertext*) env->CallIntMethod(jca, methID);
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlinkCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlinkCount
  (JNIEnv * env, jobject jca) {
	IAccessibleHypertext* ptr = GetRef(env,jca);
	long ct=0;
	HRESULT hr = ptr->get_nHyperlinks(&ct); 
	if(hr!=S_OK){
		putErrorCode(_T("hyperlinkCount"), CAccessible::getHRESULTString(hr), env, jca);
	}
	return ct;
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlink
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlink
  (JNIEnv * env, jobject jca, jint x) { 
	  IAccessibleHypertext* ptr = GetRef(env,jca);
	  IAccessibleHyperlink* hLink = NULL;
	  HRESULT hr = ptr->get_hyperlink(x, &hLink);
	  if(hr!=S_OK){
			putErrorCode(_T("hyperlink"), CAccessible::getHRESULTString(hr), env, jca);
	  }
	  return (int)hLink;
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext
 * Method:    internalGetHyperlinkIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleHypertext_internalGetHyperlinkIndex
  (JNIEnv * env, jobject jca, jint x) { 
	  IAccessibleHypertext* ptr = GetRef(env,jca);
	  long hLinkIndex = 0;
	  HRESULT hr = ptr->get_hyperlinkIndex(x, &hLinkIndex);
	  if(hr!=S_OK){
			putErrorCode(_T("hyperlinkIndex"), CAccessible::getHRESULTString(hr), env, jca);
	  }
	  return (int)hLinkIndex;
}