/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetAccessibleText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetText
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetCaretOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetCaretOffset
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetAttributes
 * Signature: (J)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetAttributes
 (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetSelectionCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetSelectionCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetSelectedText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetSelectedText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetSelectedTextStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetSelectedTextStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetSelectedTextEnd
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetSelectedTextEnd
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalAddSelection
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalAddSelection
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetCharacterBounds
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetCharacterBounds
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetOffsetAtPoint
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetOffsetAtPoint
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetTextRange
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetTextRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetTextBeforeOffset
 * Signature: (II)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetTextBeforeOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetTextAfterOffset
 * Signature: (II)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetTextAfterOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetTextAtOffset
* Signature: (II)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetTextAtOffset
  (JNIEnv *, jobject, jint, jint);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalRemoveSelection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalRemoveSelection
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalSetCaretOffset
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalSetCaretOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalSetSelection
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalSetSelection
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetCharacterCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetCharacterCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalScrollToSubstring
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalScrollToSubstring
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalScrollSubstringToPoint
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalScrollSubstringToPoint
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetNewText
 * Signature: (II)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetNewText
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText
 * Method:    internalGetOldText
 * Signature: (II)Lorg/ally/accservice/core/win32/ia2/IA2TextSegment;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleText_internalGetOldText
  (JNIEnv *, jobject);

jobject  createIA2Segment(JNIEnv* env, int startOffset,int endOffset, BSTR text);
#ifdef __cplusplus
}
#endif
#endif
