/* DO NOT EDIT THIS FILE - it is machine generated */
#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage.h"

IAccessibleImage* GetRef( JNIEnv *env, jobject jca){
    jclass cls = env->GetObjectClass(jca);
    jmethodID methID = env->GetMethodID(cls, "internalRef", "()I");
    return (IAccessibleImage*) env->CallIntMethod(jca, methID);
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetImageDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageDescription
(JNIEnv * env, jobject jca){
	IAccessibleImage* ptr = GetRef(env,jca);
	BSTR desc;
	HRESULT hr = ptr->get_description(&desc);
	  if(hr!=S_OK){
			putErrorCode(_T("imageDescription"), CAccessible::getHRESULTString(hr), env, jca);
	  }
	return CreateString(env, CComBSTR(desc));
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageHeight
(JNIEnv *env, jobject jca){
	IAccessibleImage* ptr = GetRef(env,jca);
	long ht=0;
	long wid=0;
	HRESULT hr =ptr->get_imageSize(&ht, &wid);
	  if(hr!=S_OK){
			putErrorCode(_T("imageHeight"), CAccessible::getHRESULTString(hr), env, jca);
	  }
	if( SUCCEEDED(hr)){
		return (int)ht;
	}
	return 0;
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetImageWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageWidth
(JNIEnv *env, jobject jca){
	IAccessibleImage* ptr = GetRef(env,jca);
	long ht=0;
	long wid=0;
	HRESULT hr = ptr->get_imageSize(&ht, &wid);
	  if(hr!=S_OK){
			putErrorCode(_T("imageWidth"), CAccessible::getHRESULTString(hr), env, jca);
	  }
	if( SUCCEEDED(hr)){
		return (int)wid;
	}
	return 0;
}

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetImagePosition
 * Signature: (I)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImagePosition
(JNIEnv * env, jobject jca, jint type){
	IAccessibleImage* ptr = GetRef(env,jca);
	long x=0;
	long y=0;
	HRESULT hr  = ptr->get_imagePosition((IA2CoordinateType)type, &x, &y);
	if(hr!=S_OK){
		putErrorCode(_T("imagePosition"), CAccessible::getHRESULTString(hr), env, jca);
	}
	if(SUCCEEDED(hr)){
			jclass objClass = env->FindClass("java/awt/Point");
			jmethodID ctorId = env->GetMethodID(objClass, "<init>", "(II)V");
			jobject jObj  = env->NewObject(objClass,ctorId, (jint)x, (jint)y);
			return jObj;
	}
	return 0;
}