/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
////#include "StdString.h"
#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalGetAccessibleActionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalGetActionCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalDoAccessibleAction
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalDoAccessibleAction
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalGetAccessibleActionDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalGetActionDescription
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalGetAccessibleActionKeyBinding
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalGetActionKeyBinding
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalGetAccessibleActionName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalGetActionName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction
 * Method:    internalGetLocalizedAccessibleActionName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleAction_internalGetLocalizedAccessibleActionName
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
