/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetColumnExtent
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetColumnExtent
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetColumnHeaderCells
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetColumnHeaderCells
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetColumnIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetColumnIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetRowExtent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetRowExtent
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetRowHeaderCells
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetRowHeaderCells
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetRowIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetRowIndex
  (JNIEnv *, jobject);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalIsSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalIsSelected
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetRowColumnExtents
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetRowColumnExtents
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell
 * Method:    internalGetTable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IAccessibleTableCell_internalGetTable
 (JNIEnv * env, jobject jca);

IAccessibleTable2* getTableFromIUnk(IUnknown *iUnk);

#ifdef __cplusplus
}
#endif
#endif
