/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleTableCaption
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetTableCaption
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleTableSummary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetTableSummary
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleTableColumnCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetTableColumnCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleTableRowCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetTableRowCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleColumnDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetColumnDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleRowDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetRowDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedAccessibleColumns
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedAccessibleColumns
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedAccessibleRows
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedAccessibleRows
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleCell
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleIndex
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetIndex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleColumnExtentAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetColumnExtentAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleColumnHeaders
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetColumnHeaders
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleColumnIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetColumnIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedColumnCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedColumnCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedRowCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedRowCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleRowExtentAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetRowExtentAt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleRowHeaders
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetRowHeaders
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetAccessibleRowIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetRowIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalIsColumnSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalIsColumnSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalIsRowSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalIsRowSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalIsAccessibleSelected
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalIsAccessibleSelected
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalSelectAccessibleColumn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalSelectAccessibleColumn
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalSelectAccessibleRow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalSelectAccessibleRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalUnselectAccessibleColumn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalUnselectAccessibleColumn
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalUnselectAccessibleRow
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalUnselectAccessibleRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetRowColumnExtentsAtIndex
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetRowColumnExtentsAtIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetModelChange
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetModelChange
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedChildCount
 (JNIEnv * env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable
 * Method:    internalGetSelectedChildren
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleTable_internalGetSelectedChildren
(JNIEnv *, jobject );
#ifdef __cplusplus
}
#endif
#endif
