/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"


/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetAccessibleImageDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetAccessibleImageHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetAccessibleImageWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImageWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage
 * Method:    internalGetImagePosition
 * Signature: (I)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleImage_internalGetImagePosition
(JNIEnv * env, jobject jca, jint type);

#ifdef __cplusplus
}
#endif
#endif
