/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sstream>
using namespace std;
//#include "StdString.h"
//#include "Accessible.h"
#include "CAccessible2.h"


/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    getNativeHwnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetWindowHandle
(JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    getNativeChildID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetChildId
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalDispose
  (JNIEnv *, jobject);

	/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalInitFromHwnd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalInitFromHwnd
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalInitFromHtmlElement
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalInitFromHtmlElement
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalInitFromPoint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalInitFromPoint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleValue2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleValue2
  (JNIEnv *, jobject);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleAction2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleAction2
  (JNIEnv *, jobject);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleComponent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleComponent
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleHyperLink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleHyperLink
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleHyperText
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleHyperText
  (JNIEnv *, jobject);
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleValueMin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleValueMin
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleValueMax
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleValueMax
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleTable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleTable
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible2
 * Method:    internalGetAccessibleTable2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleTable2
(JNIEnv * env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible2
 * Method:    internalGetAccessibleTableCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleTableCell
(JNIEnv * env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleText
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleText
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleImage
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleImage
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleRole
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleRole
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleRoleAsLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleRoleAsLong
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleStateAsLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleStateAsLong
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleApplication
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleApplication
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleChildCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetIA2AccessibleChildren
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetIA2AccessibleChildren
  (JNIEnv *env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleChild
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetIA2AccessibleChild
  (JNIEnv *env, jobject jca, jint childID);


JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccParent
  (JNIEnv *, jobject );

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    returnIA2Accessible
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_returnIA2Accessible
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalIsIA2Accessible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalIsIA2Accessible
  (JNIEnv *, jclass, jint);


JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetIA2fromIAcc
(JNIEnv *env, jclass cls , jint iAcc);
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleEditableText
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleEditableText
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetNRelations
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetNRelations
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleRelation
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleRelation
(JNIEnv * , jobject , jint );

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAccessibleRelations
 * Signature: ()[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAccessibleRelations
(JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalScrollTo
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalScrollTo
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalScrollTo
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalScrollToPoint
(JNIEnv * env, jobject jca, jint coordinateType, jint x, jint y );
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetGroupPosition
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetGroupPosition
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetLocalizedRoleName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetLocalizedRoleName
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetStates
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetStates
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetLocalizedStateNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetLocalizedStateNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetExtendedRole
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetExtendedRole
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetLocalizedExtendedRole
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetLocalizedExtendedRole
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetExtendedStateCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetExtendedStateCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetExtendedStates
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetExtendedStates
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetLocalizedExtendedStates
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetLocalizedExtendedStates
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetUniqueID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetUniqueID
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetIA2WindowHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetIA2WindowHandle
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetIndexInParent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetIndexInParent
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetLocale
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetLocale
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible
 * Method:    internalGetAttributes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAttributes
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible_internalGetAddress
  (JNIEnv *env, jobject jca);

JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibilityEventService_createAccessibleObjectFromEvent
	(JNIEnv * pEnv, jclass jcls, jint hwnd, jint idObject, jint idChild );

jstring CreateString (JNIEnv*, CComBSTR);

CAccessible2* GetCppRef( JNIEnv *env, jobject jca);

//int getRelationTarget(int index, IAccessibleRelation* accRel);

jobject getString(VARIANT val, JNIEnv* env);

JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibilityService_internalCoInitialize
(JNIEnv * env, jclass jcls);

JNIEXPORT void JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibilityService_internalCoUnInitialize
(JNIEnv * env, jclass jcls);

#ifdef __cplusplus
}
#endif
#endif
