/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
 * Method:    internalGetCurrentAccessibleValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue_internalGetCurrentValue
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
 * Method:    internalSetCurrentAccessibleValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue_internalSetCurrentAccessibleValue
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
 * Method:    internalGetAccessibleValueMax
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue_internalGetValueMax
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue
 * Method:    internalGetAccessibleValueMin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleValue_internalGetValueMin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
