/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "StdString.h"

#include "org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent
 * Method:    internalGetLocation
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent_internalGetLocation
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent
 * Method:    internalGetForeground
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent_internalGetForeground
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent
 * Method:    internalGetBackground
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_ia2_IA2AccessibleComponent_internalGetBackground
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
