/* DO NOT EDIT THIS FILE - it is machine generated */

#include "Accessible.h"

#include <gdiplus.h>
#include <iostream>
using namespace Gdiplus;

int penWidth = 3;

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible */

#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    getNativeHwnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetWindowHandle
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAddress
  (JNIEnv *env, jobject jca);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    getNativeChildID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetChildId
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalInitFromHwnd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalInitFromHwnd
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalInitFromHtmlElement
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalInitFromHtmlElement
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalInitFromPoint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalInitFromPoint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalDispose
  (JNIEnv *, jobject);


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalDrawRectangle
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalDrawRectangle
(JNIEnv *env, jobject jca, jint x, jint y, jint wt, jint ht);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalEraseRectangle
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalEraseRectangle
(JNIEnv *, jobject , jint, jint , jint , jint );

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalEraseRectangle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalEraseDesktop
(JNIEnv *, jclass  );
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetClassNameFromHwnd
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetClassNameFromHwnd
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleParent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleParent
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleChildCount
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleChildren
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleChildren
  (JNIEnv *, jobject);
/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleChild
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalHasFocus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalHasFocus
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleName
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleValue
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleHelp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleHelp
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleKeyboardShortcut
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleKeyboardShortcut
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleAction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleAction
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleRole
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleRole
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleRoleAsInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleRoleAsInt
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleState
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleSelection
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleSelection
  (JNIEnv *, jobject);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalGetAccessibleLocation
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleLocation
  (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalPutValue
(JNIEnv *env, jobject jca, jint childId, jstring value);

JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalDoDefaultAction
  (JNIEnv *env, jobject jca, jint val);

JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalSelect
  (JNIEnv *env, jobject jca, jint flag, jint val);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible
 * Method:    internalLocation
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalLocation
  (JNIEnv *, jobject, jint);

JNIEXPORT jstring JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessible_internalGetAccessibleHelpTopic
  (JNIEnv *env, jobject jca);

CAccessible* GetCppObjectRef (JNIEnv*, jobject);

//jstring CreateString (JNIEnv*, CComBSTR);

jstring CreateString(JNIEnv *env, CComBSTR str);

bool INIT_ACC_CHILDID_SELF;
int ACC_CHILDID_SELF;

#ifdef __cplusplus
}
#endif
#endif
