/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "Accessible.h"

/* Header for class org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService */

UINT uThreadId;
static JNIEnv* g_Env = NULL;
static jobject g_obj = NULL;

// cache for the instance handle
HINSTANCE hInstance;
UINT EVENT_DATA_READY;

// declarations
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
void RegisterWindowClass();
void Callback();
void ErrorHandler(LPSTR);


#ifndef _Included_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
#define _Included_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    internalSetWinEventHook
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_internalSetWinEventHook
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    internalRemoveWinEventHook
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_internalRemoveWinEventHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    internalGetClockTicks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_internalGetClockTicks
  (JNIEnv *, jclass);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    createFileMapping
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_createFileMapping
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    openFileMapping
 * Signature: (IZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_openFileMapping
  (JNIEnv *, jclass, jint, jboolean, jstring);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    mapViewOfFile
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_mapViewOfFile
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    unmapViewOfFile
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_unmapViewOfFile
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    writeToMem
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_writeToMem
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    readFromMem
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_readFromMem
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    closeHandle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_closeHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService
 * Method:    initThread
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_initThread
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityEventService_createAccessibleObjectFromEvent
	(JNIEnv * pEnv, jclass jcls, jint hwnd, jint idObject, jint idChild ) ;

JNIEXPORT jboolean JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityService_internalCoInitialize
(JNIEnv * env, jclass jcls);

JNIEXPORT void JNICALL Java_org_a11y_utils_accprobe_accservice_core_win32_msaa_MsaaAccessibilityService_internalCoUnInitialize
(JNIEnv * env, jclass jcls);

#ifdef __cplusplus
}
#endif
#endif
